index:
  path: /
  controller: App\Controller\IndexController::index
  methods: GET
qr_code:
  path: /qr_code/{data}.png
  controller: App\Controller\QrCodeController::qrCode
  methods: GET
generate_data:
  path: /generate_data
  controller: App\Controller\QrCodeController::generateData
  methods: POST
